services:
  api:
    image: ghcr.io/kralluz/backendteapoio:${TAG:-latest}
    build:
      context: .
      dockerfile: Dockerfile
      no_cache: true

    container_name: teapoio-api

    environment:
      - NODE_ENV=production
      - PORT=3333
      - API_HOST=0.0.0.0
      # Aumentar limite de memória do Node.js para 4GB
      - NODE_OPTIONS=--max-old-space-size=4096
      - DATABASE_URL=${DATABASE_URL}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_REFRESH_SECRET=${JWT_REFRESH_SECRET:-default_refresh_secret}
      - ACCESS_TOKEN_EXPIRY=${ACCESS_TOKEN_EXPIRY:-45m}
      - REFRESH_TOKEN_EXPIRY=${REFRESH_TOKEN_EXPIRY:-8h}
      - SEED_DATABASE=${SEED_DATABASE:-false}
      - FRONTEND_URL=${FRONTEND_URL:-http://localhost:3000}

    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3333/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 40s

    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

    deploy:
      mode: replicated
      replicas: 1

      resources:
        limits:
          cpus: '2.0'
          memory: 4G
        reservations:
          cpus: '0.5'
          memory: 512M

      restart_policy:
        condition: any

      update_config:
        parallelism: 1
        delay: 10s

      rollback_config:
        parallelism: 1
        delay: 10s

      endpoint_mode: vip

    ports:
      - "3333:3333"

    volumes:
      - uploads_data:/app/uploads
      - logs_data:/app/logs

volumes:
  uploads_data:
    driver: local
  logs_data:
    driver: local
